services:
  postgres:
    image: postgres:15
    container_name: antonio
    restart: always
    environment:
      POSTGRES_USER: felipao
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: lava_tech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynet

  pgadmin:
    image: dpage/pgadmin4:9.8.0
    container_name: lava_tech
    environment:
      PGADMIN_DEFAULT_EMAIL: gremio@gmail.com
      PGADMIN_DEFAULT_PASSWORD: internacional
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mynet

networks:
   mynet:
    driver: bridge
volumes:
  postgres_data:
